AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'

Description: "update website visitor counter exposed in API Gateway REST API from DynamoDB"

Resources: 
  dynamodbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - 
          AttributeName: website_id
          AttributeType: S
      
      KeySchema:
        - 
          AttributeName: website_id
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  lambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: 
      MemorySize: 128
      Role: role-arn
      Runtime: python3.7
      Timeout: 3
      Code: 
        ZipFile: |
          import json
          import boto3

          def lambda_handler(event, context):
            return "Hello World"

Outputs:
  DynamodbTable-Name:
    Value: !GetAtt dynamodbTable.TableName
  lambdaFunction-Name:
    Value: !GetAtt lambdaFunction.FunctionName

